### Create with POST

###
GET http://localhost:3000/local/v3.3b/ed-fi/contentClassDescriptors

### Created an EducationContents record
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents

{
    "contentIdentifier": "933zsd4350",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Get all EducationContents records
GET http://localhost:3000/local/v3.3b/ed-fi/EducationContents


### Get the created record (lower case)
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/4a7d89fd5b4247a526bee49d28b97c7eead5f2d73b5982e23fb518a8


### Update the created record
PUT http://localhost:3000/local/v3.3b/ed-fi/educationContents/4a7d89fd5b4247a526bee49d28b97c7eead5f2d73b5982e23fb518a8

{
    "contentIdentifier": "933zsd4350",
    "namespace": "4321",
    "shortDescription": "abc+",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Delete the created record
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/4a7d89fd5b4247a526bee49d28b97c7eead5f2d73b5982e23fb518a8

### Strict validation is enabled, this will fail due to an invalid country
POST http://localhost:3000/local/v3.3b/ed-fi/students
reference-validation: true

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#AD3"
}

### Strict validation is disabled, but that doesn't impact the descriptor validation
POST http://localhost:3000/local/v3.3b/ed-fi/students
reference-validation: false

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#AD3"
}

### Now it contains a valid country
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
reference-validation: false

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### Wrong case on the 'N' below - expect 404
GET http://localhost:3000/local/v3.3b/ed-fi/students/
#?lastSurName=World

### Correct case
GET http://localhost:3000/local/v3.3b/ed-fi/students/?lastSurname=World

### Update this student
PUT http://localhost:3000/local/v3.3b/ed-fi/students/ffa42cab9ad99bdc7ab8cc9c36491bcd9047a11438f4ade104492cb0
reference-validation: false

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#CA"
}

### Fails with 404 - can't post an abstract entity
POST http://localhost:3000/local/v3.3b/ed-fi/educationOrganizations

{
    "schoolId": 99,
    "categories": [],
    "gradeLevels": []
}

### Fails - note reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations
reference-validation: true

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "interventionReference": {
        "interventionIdentificationCode": "111",
        "educationOrganizationId": 99
    }
}

### Succeeds despite intervention code not existing - note reference-validation: false
POST http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations
reference-validation: false

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "interventionReference": {
        "interventionIdentificationCode": "111",
        "educationOrganizationId": 99
    }
}


#### Strict validation is off, but still fails due to an invalid descriptor
POST http://localhost:3000/local/v3.3b/ed-fi/sections
reference-validation: false

{ 
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z2"
            }
        }
    ]
}


### Create a location - school does not exist.
## This has an unusual error message - complains about educationOrganizationId not existing because it is renamed schoolId by School.
POST http://localhost:3000/local/v3.3b/ed-fi/locations
reference-validation: true

{
  "classroomIdentificationCode": "string",
  "schoolReference": {
    "schoolId": 99
  },
  "maximumNumberOfSeats": 20,
  "optimalNumberOfSeats": 10
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/sessions
descriptor-validation: false

{
  "sessionName": "d",
  "schoolYear": 2034,
  "beginDate": "2021-01-01",
  "endDate": "2021-06-01",
  "termDescriptor": "uri://ed-fi.org/TermDescriptor#Spring Semester",
  "totalInstructionalDays": 90,
  "schoolReference": {
    "schoolId": 122
  }
}

######## Following tests verify delete referential integrity checks. Must run local.33b.assignable.http first.
POST http://localhost:3000/local/v3.3b/ed-fi/courseOfferings

{ 
    "localCourseCode": "abfdddcde",
    "courseReference": {
        "courseCode": "1234",
        "educationOrganizationId": 12
    },
    "schoolReference": {
        "schoolId": 122
    },
    "sessionReference": {
        "schoolId": 122,
        "sessionName": "d",
        "schoolYear": 2034
    }
}


### Create a location
POST http://localhost:3000/local/v3.3b/ed-fi/locations
reference-validation: true

{
  "classroomIdentificationCode": "string",
  "schoolReference": {
    "schoolId": 122
  },
  "maximumNumberOfSeats": 20,
  "optimalNumberOfSeats": 10
}

### Create a section that references that courseOffering. Should cause deletion to fail
POST http://localhost:3000/local/v3.3b/ed-fi/sections

{ 
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
      "localCourseCode": "abfdddcde",
      "schoolId": 122,
      "schoolYear": 2034,
      "sessionName": "d"
    },
    "locationReference": {
      "classroomIdentificationCode": "string",
      "schoolId": 122
    }
}

### Should fail due to the presence of the section above
DELETE http://localhost:3000/local/v3.3b/ed-fi/courseOfferings/234e2415074c782efb93362c62926a5c48ece972b52b7e9010fa6280

### If the above failed, now try deleting the section and then run above again. Should work now - if the TREFs were deleted
DELETE http://localhost:3000/local/v3.3b/ed-fi/sections/d6f94aa9b424e4004eaa4a81cb00ae58775c5d317472d5adb1cb10b0

######## List all with GET
GET http://localhost:3000/local/v3.3b/ed-fi/StudentEducationOrganizationAssociations

###
GET http://localhost:3000/local/v3.3b/ed-fi/students

###
GET http://localhost:3000/local/v3.3b/ed-fi/SexDescriptors

### Lowercase
GET http://localhost:3000/local/v3.3b/ed-fi/behaviorDescriptors

###
GET http://localhost:3000/local/v3.3b/ed-fi/BehaviorDescriptors/465b82d03e4146094405a9fdb32d311c236ef3b0d534b0274053f67c


### 
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencies

{
    "localEducationAgencyId": 2231,
    "nameOfInstitution": "Grand Bend School District",
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent",
    "categories": []
}

####
POST http://localhost:3000/local/v3.3b/ed-fi/Courses

{
    "educationOrganizationReference": {
        "educationOrganizationId": 2231
    },
    "courseCode": "1234",
    "courseTitle": "A Course",
    "numberOfParts": 1,
    "identificationCodes": []
}


####
POST http://localhost:3000/local/v3.3b/ed-fi/StudentEducationOrganizationAssociations

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 2231
    },
    "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Female"
}


####
POST http://localhost:3000/local/v3.3b/ed-fi/studentSchoolAssociations
descriptor-validation: false

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "schoolReference": {
        "schoolId": 122
    },
    "entryDate": "2020-01-01",
    "entryGradeLevelDescriptor": "10"
}

######## GET by ID
GET http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations/4239e9771c21da48596769748893ba634c28466be1286cd2226b9b93
x-security-edorgid: 231
zzzzzx-security-studentid: 777
x-security-through: StudentEducationOrganizationAssociation

###### GET Query
GET http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations?interventionReference.interventionIdentificationCode=111
x-security-edorgid: 232,231
x-security-through: StudentEducationOrganizationAssociation
x-security-studentid: 777

### MetaEd model metadata with GET

GET http://localhost:3000/local/metaed/v3.3b

### Base request to get DS version and supported extensions

GET http://localhost:3000/local

### Entity does not exist
GET http://localhost:3000/local/v3.3b/ed-fi/SacademicWeeks

### Descriptor does not exist
GET http://localhost:3000/local/v3.3b/ed-fi/b3haviorDescriptors


###
GET http://localhost:3000/local/v3.3b/ed-fi/GeneralStudentProgramAssociations

### RND-149: Account/AccountCode shape is wrong
POST http://localhost:3000/local/v3.3b/ed-fi/accounts
reference-validation: false

{
    "educationOrganizationReference": {
      "educationOrganizationId": 255901
    },
    "accountIdentifier": "1.200.100.10001",
    "fiscalYear": 2012,
    "accountName": "RegularInstructionsss",
    "accountCodes": [
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "100"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "101"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "102"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "103"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "104"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "105"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "106"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "107"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "108"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "109"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "110"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "111"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "112"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "113"
        }
      }
    ]
}

### delete the record above
# Manually confirm that all references were removed:
# select * from "edfi-meadowlark-local" where
#   (begins_with(pk, 'TREF') and sk = 'FREF#ID#a5d4132d14db015714ab08184174812ea09ec358d99a4bc3fb958306')
#   or (pk = 'FREF#ID#a5d4132d14db015714ab08184174812ea09ec358d99a4bc3fb958306')
DELETE http://localhost:3000/local/v3.3b/ed-fi/accounts/a5d4132d14db015714ab08184174812ea09ec358d99a4bc3fb958306


###
# Limit/Offset/TotalCount Testing: ODS/API supports query parameters "limit", "offset", and "totalcount" for special
# purposes. Meadowlark does not yet support these values. The following queries should all return 200,
# thus indicating that the three terms are ignored.
GET http://localhost:3000/local/v3.3b/ed-fi/students/?limit=1&offset=2&totalCount=true
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInN1YiI6InN1cGVyLWdyZWF0LVNJUyIsImp0aSI6IjNkNTliNzVmLWE3NjItNGJhYS05MTE2LTE5YzgyZmRmOGRlMyIsImlhdCI6MTYzNjU2MjA2MCwiZXhwIjozODQ1NTQ4ODgxfQ.WF5ABFZAvNsLDZktwa8VxDR846fGptRXJObtQitbL8I
