version: "3.8"

volumes:
  esdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: elasticsearch-node1
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=elasticsearch-node1
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elasticpassword
      - xpack.security.enabled=false
    mem_limit: 2g

  kibana:
    image: kibana:latest
    environment:
      - xpack.security.enabled=false
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch-node1
