apiVersion: v1
kind: Service
metadata:
  labels:
    serviceName: meadowlark-api-ml-local-1
  name: meadowlark-api-ml-local-1
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  selector:
    serviceName: meadowlark-api-ml-local-1
status:
  loadBalancer: {}
