apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    serviceName: opensearch-ml-local-data
  name: opensearch-ml-local-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
