apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: opensearch-ml-local
  name: opensearch-ml-local
spec:
  ports:
    - name: "9201"
      port: 9201
      targetPort: 9200
    - name: "9601"
      port: 9601
      targetPort: 9600
  selector:
    io.kompose.service: opensearch-ml-local
status:
  loadBalancer: {}
