apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    serviceName: pgsql-ml-data
  name: pgsql-ml-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
