apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serviceName: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      serviceName: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/meadowlark-js-default: "true"
        serviceName: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: abcdefgh1!
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14.3-alpine@sha256:84c6ea4333ae18f25ea0fb18bb142156f2a2e545e0a779d93bbf08079e56bdaf
          name: postgres-ml
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgsql-ml-data
      hostname: postgres
      restartPolicy: Always
      volumes:
        - name: pgsql-ml-data
          persistentVolumeClaim:
            claimName: pgsql-ml-data
status: {}
