apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    serviceName: postgres
spec:
  selector:
    serviceName: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
