apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    serviceName: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    serviceName: postgres
status:
  loadBalancer: {}
