# These tests are intended to validate handling of superclass relationships.
# - Can we create entities that have a superclass, e.g. a School (superclass: Education Organization)?
# - Can we access that created entity correctly?
# - When a request comes in with a document that references an Education Organization, can we validate the
#   educationOrganizationId properly even though there is no "educationOrganization" entity?

@auth_header=Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInJvbGVzIjpbInZlbmRvciJdLCJzdWIiOiJzdXBlci1ncmVhdC1TSVMiLCJqdGkiOiIyNGMyMDIyMC1mMjg1LTRlNjMtYThmNC1iMmRkYzM5MzAwMDQiLCJpYXQiOjE2NTg1MjM0MDgsImV4cCI6MjY1ODUyNzAwOH0.S2C44HoFMr5ZYSUkbZoAV2pz7Z1Xi40yynH17GOBVoY

###
POST http://localhost:3000/local/v3.3b/ed-fi/countryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "US",
    "shortDescription": "US",
    "namespace": "uri://ed-fi.org/CountryDescriptor"
}


###
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
{{auth_header}}
reference-validation: true

{ 
    "studentUniqueId": "abc",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### 
GET http://localhost:3000/local/v3.3b/ed-fi/schools
{{auth_header}}


###
GET http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
{{auth_header}}


###
POST http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "All Levels",
    "shortDescription": "All Levels",
    "namespace": "uri://ed-fi.org/SchoolCategoryDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}


###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "School",
    "shortDescription": "School",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

### 
# @name school122
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "schoolId": 122,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": []
}

### 
@schoolDocumentlocation = {{school122.response.headers.location}}
GET http://localhost:3000{{schoolDocumentlocation}}
{{auth_header}}

### 
PUT http://localhost:3000{{schoolDocumentlocation}}
content-type: application/json
{{auth_header}}

{
    "schoolId": 122,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": []
}

### 
DELETE http://localhost:3000{{schoolDocumentlocation}}
{{auth_header}}


###
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencyCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Independent",
    "shortDescription": "Independent",
    "namespace": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor"
}


###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Local Education Agency",
    "shortDescription": "Local Education Agency",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

### 
# @name lea12
POST http://localhost:3000/local/v3.3b/ed-fi/localEducationAgencies
content-type: application/json
{{auth_header}}
reference-validation: false

{
    "localEducationAgencyId": 12,
    "nameOfInstitution": "A LEA",
    "categories" : [
        {
            "educationOrganizationCategoryDescriptor": "something"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent"
}

###
@schoolDocumentLocation = {{lea12.response.headers.location}}
GET http://localhost:3000{{schoolDocumentLocation}}
{{auth_header}}

### 
PUT http://localhost:3000{{schoolDocumentLocation}}
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "localEducationAgencyId": 12,
    "nameOfInstitution": "A LEA",
    "categories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Local Education Agency"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent"
}

### 
DELETE http://localhost:3000{{schoolDocumentLocation}}
{{auth_header}}


### 
GET http://localhost:3000/local/v3.3b/ed-fi/schools
{{auth_header}}

### 
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "schoolId": 122,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": []
}

####
POST http://localhost:3000/local/v3.3b/ed-fi/courses
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "educationOrganizationReference": {
        "educationOrganizationId": 122
    },
    "courseCode": "1234",
    "courseTitle": "A Course",
    "numberOfParts": 1,
    "identificationCodes": []
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/SexDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Female",
    "shortDescription": "Female",
    "namespace": "uri://ed-fi.org/SexDescriptor"
}

####
POST http://localhost:3000/local/v3.3b/ed-fi/studentEducationOrganizationAssociations
content-type: application/json
{{auth_header}}
reference-validation: true

{ 
    "studentReference": {
        "studentUniqueId": "abc"
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 122
    },
    "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Female"
}



### 
# Don't delete this! Used by tests in other files.
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "schoolId": 123,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": []
}


###
GET http://localhost:3000/local/v3.3b/ed-fi/schools?schoolId=123
{{auth_header}}

###
# These set of tests are to show that given a speific type of education organization (in this case
# a school) Make sure to 

### Create a LocalEducationAgencyCategory Descriptor
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencyCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Independent",
    "shortDescription": "Independent",
    "namespace": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor"
}
### Create a LocalEducationAgency
POST http://localhost:3000/local/v3.3b/ed-fi/localEducationAgencies
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "localEducationAgencyId": 125,
    "nameOfInstitution": "A School",
    "categories":[],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent"
}

### Create a location with a LEA - should fail
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "schoolReference":{
        "schoolId": 125
    },
    "classroomIdentificationCode":"Test Assigning LEA"
}

### Atempt to assign School to location - Should succeed
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "schoolReference":{
        "schoolId": 123
    },
    "classroomIdentificationCode":"Test Assigning School"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}
reference-validation: true

{
    "schoolId": 124,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [],
    "schoolCategories": [],
    "gradeLevels": []
}