##
## Not yet functioning 2022-06-16 
## 


### Authenticate
# @name client1
POST http://localhost:3000/local/api/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

###
@authToken1 = {{client1.response.body.$.access_token}}

#
## Graduation Plans
# Core problem: schoolyear. This may be related to RND-131. The sample payload
# comes straight from the ODS/API 5.3.x.
#

###
GET http://localhost:3000/local/v3.3b/ed-fi/graduationPlans
authorization: bearer {{authToken1}}

###
POST http://localhost:3000/local/v3.3b/ed-fi/graduationPlans
authorization: bearer {{authToken1}}
content-type: application/json

{
  "educationOrganizationReference": {
    "educationOrganizationId": 255901
  },
  "graduationSchoolYearTypeReference": {
    "schoolYear": 2016
  },
  "graduationPlanTypeDescriptor": "uri://ed-fi.org/GraduationPlanTypeDescriptor#Recommended",
  "totalRequiredCredits": 28
}

#
## Parents
#

###
GET http://localhost:3000/local/v3.3b/ed-fi/parents
authorization: bearer {{authToken1}}

###
POST http://localhost:3000/local/v3.3b/ed-fi/sexDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Male",
  "shortDescription": "Male",
  "namespace": "uri://ed-fi.org/SexDescriptor"
}

#
## PostSecondaryInstitutions
#

### Test these next ones after fixing errors above as well as RND-295

###
POST http://localhost:3000/local/v3.3b/ed-fi/postSecondaryInstitutions
authorization: bearer {{authToken1}}
content-type: application/json

{
    "postSecondaryInstitutionId": 6000203,
    "nameOfInstitution": "The University of Texas at Austin",
    "operationalStatusDescriptor": "uri://ed-fi.org/OperationalStatusDescriptor#Active",
    "shortNameOfInstitution": "UT-Austin",
    "webSite": "https://www.utexas.edu/",
    "postSecondaryInstitutionLevelDescriptor": "uri://ed-fi.org/PostSecondaryInstitutionLevelDescriptor#Four or more years",
    "addresses": [],
    "categories": [
        {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Post Secondary Institution"
        }
    ],
    "identificationCodes": [],
    "indicators": [],
    "institutionTelephones": [
        {
        "institutionTelephoneNumberTypeDescriptor": "uri://ed-fi.org/InstitutionTelephoneNumberTypeDescriptor#Main",
        "telephoneNumber": "(512) 471-3434"
        }
    ],
    "internationalAddresses": [],
    "mediumOfInstructions": []
}


#
## EducationServiceCenters
#

###
POST http://localhost:3000/local/v3.3b/ed-fi/educationOrganizationCategoryDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Education Service Center",
  "shortDescription": "Education Service Center",
  "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptors"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/educationServiceCenters
authorization: bearer {{authToken1}}
content-type: application/json

{
    "educationServiceCenterId": 255950,
    "nameOfInstitution": "Region 99 Education Service Center",
    "addresses": [
      {
        "addressTypeDescriptor": "uri://ed-fi.org/AddressTypeDescriptor#Mailing",
        "city": "Dallas",
        "postalCode": "75217",
        "stateAbbreviationDescriptor": "uri://ed-fi.org/StateAbbreviationDescriptor#TX",
        "streetNumberName": "P.O. Box 898",
        "nameOfCounty": "Dallas",
        "periods": []
      },
      {
        "addressTypeDescriptor": "uri://ed-fi.org/AddressTypeDescriptor#Physical",
        "city": "Dallas",
        "postalCode": "75217",
        "stateAbbreviationDescriptor": "uri://ed-fi.org/StateAbbreviationDescriptor#TX",
        "streetNumberName": "898 Texas Education Blvd.",
        "nameOfCounty": "Dallas",
        "periods": []
      }
    ],
    "categories": [
      {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Education Service Center"
      }
    ],
    "identificationCodes": [
      {
        "educationOrganizationIdentificationSystemDescriptor": "uri://ed-fi.org/EducationOrganizationIdentificationSystemDescriptor#NCES",
        "identificationCode": "255950"
      }
    ],
    "indicators": [],
    "institutionTelephones": [
      {
        "institutionTelephoneNumberTypeDescriptor": "uri://ed-fi.org/InstitutionTelephoneNumberTypeDescriptor#Fax",
        "telephoneNumber": "(214) 876-8921"
      },
      {
        "institutionTelephoneNumberTypeDescriptor": "uri://ed-fi.org/InstitutionTelephoneNumberTypeDescriptor#Main",
        "telephoneNumber": "(214) 876-8290"
      }
    ],
    "internationalAddresses": []
  }