# These tests are intended to validate handling of superclass relationships.
# - Can we create entities that have a superclass, e.g. a School (superclass: Education Organization)?
# - Can we access that created entity correctly?
# - When a request comes in with a document that references an Education Organization, can we validate the
#   educationOrganizationId properly even though there is no "educationOrganization" entity?

### Authenticate
# @name client1
POST http://localhost:3000/local/api/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

###
@auth_header=Authorization: bearer {{client1.response.body.$.access_token}}

### Authenticate client4 (this client has validation turned off
# @name client4
POST http://localhost:3000/local/api/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_4",
    "client_secret": "meadowlark_secret_4"
}
###
@auth_header4=Authorization: bearer {{client4.response.body.$.access_token}}
###

###
POST http://localhost:3000/local/v3.3b/ed-fi/countryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "US",
    "shortDescription": "US",
    "namespace": "uri://ed-fi.org/CountryDescriptor"
}


###
# @name studentabc
# reference-validation: true
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
{{auth_header}}

{ 
    "studentUniqueId": "abc",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### 
@studentDocumentlocation = {{studentabc.response.headers.location}}
DELETE http://localhost:3000{{studentDocumentlocation}}
{{auth_header}}

### 
GET http://localhost:3000/local/v3.3b/ed-fi/schools
{{auth_header}}


###
GET http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
{{auth_header}}


###
POST http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "All Levels",
    "shortDescription": "All Levels",
    "namespace": "uri://ed-fi.org/SchoolCategoryDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/GradeLevelDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "First Grade",
    "shortDescription": "First Grade",
    "namespace": "uri://ed-fi.org/GradeLevelDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}


###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "School",
    "shortDescription": "School",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

### 
# @name school122
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}

{
    "schoolId": 122,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
        }
    ]
}

### 
@schoolDocumentlocation = {{school122.response.headers.location}}
GET http://localhost:3000{{schoolDocumentlocation}}
{{auth_header}}

### 
PUT http://localhost:3000{{schoolDocumentlocation}}
content-type: application/json
{{auth_header}}

{
    "schoolId": 122,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": [
        {"gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"}
    ]
}

### 
DELETE http://localhost:3000{{schoolDocumentlocation}}
{{auth_header}}


###
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencyCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Independent",
    "shortDescription": "Independent",
    "namespace": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor"
}


###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Local Education Agency",
    "shortDescription": "Local Education Agency",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

### 
# reference-validation: false
# @name lea12
POST http://localhost:3000/local/v3.3b/ed-fi/localEducationAgencies
content-type: application/json
{{auth_header4}}

{
    "localEducationAgencyId": 12,
    "nameOfInstitution": "A LEA",
    "categories" : [
        {
            "educationOrganizationCategoryDescriptor": "something"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent"
}

###
@schoolDocumentLocation = {{lea12.response.headers.location}}
GET http://localhost:3000{{schoolDocumentLocation}}
{{auth_header}}

### 
# reference-validation: true
PUT http://localhost:3000{{schoolDocumentLocation}}
content-type: application/json
{{auth_header}}

{
    "localEducationAgencyId": 12,
    "nameOfInstitution": "A LEA",
    "categories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Local Education Agency"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent"
}

### 
DELETE http://localhost:3000{{schoolDocumentLocation}}
{{auth_header}}


### 
GET http://localhost:3000/local/v3.3b/ed-fi/schools
{{auth_header}}

### 
# @name school250
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}

{
    "schoolId": 250,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
        }
    ]
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/CourseIdentificationSystemDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "namespace": "uri://ed-fi.org/CourseIdentificationSystemDescriptors"
}

####
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/courses
content-type: application/json
{{auth_header}}

{
    "educationOrganizationReference": {
        "educationOrganizationId": 250
    },
    "courseCode": "1234",
    "courseTitle": "A Course",
    "numberOfParts": 1,
    "identificationCodes": [
        {
            "identificationCode":"testId",
            "courseIdentificationSystemDescriptor":"uri://ed-fi.org/CourseIdentificationSystemDescriptor#Other"
        }
    ]
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/SexDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Female",
    "shortDescription": "Female",
    "namespace": "uri://ed-fi.org/SexDescriptor"
}

####
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/studentEducationOrganizationAssociations
content-type: application/json
{{auth_header}}

{ 
    "studentReference": {
        "studentUniqueId": "abc"
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 250
    },
    "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Female"
}

### Attempt to delete the school, this should fail with a Status Code of 409 due existing references
@school250Documentlocation = {{school250.response.headers.location}}
DELETE http://localhost:3000{{school250Documentlocation}}
{{auth_header}}


### 
# Don't delete this! Used by tests in other files.
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}

{
    "schoolId": 123,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
        }
    ]
}


###
GET http://localhost:3000/local/v3.3b/ed-fi/schools?schoolId=123
{{auth_header}}

###
# Verify that when a specific subclass type is referenced on an entity, that only that type can be referenced, trying to 
# reference another subclass should fail 

### Create a LocalEducationAgencyCategory Descriptor
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencyCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Independent",
    "shortDescription": "Independent",
    "namespace": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor"
}

### Create a LocalEducationAgency
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/localEducationAgencies
content-type: application/json
{{auth_header}}

{
    "localEducationAgencyId": 125,
    "nameOfInstitution": "A School",
      "categories" : [
        {
         "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent"
}

### Create a location with a LEA - should fail with 400 - Bad Request
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
{{auth_header}}

{
    "schoolReference":{
        "schoolId": 125
    },
    "classroomIdentificationCode":"Test Assigning LEA"
}

### Create School
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}

{
    "schoolId": 124,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
        }
    ]
}

### Atempt to assign School to location - Should succeed
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
{{auth_header}}

{
    "schoolReference":{
        "schoolId": 124
    },
    "classroomIdentificationCode":"Test Assigning School"
}
