##### START AUTHENTICATION SETUP

@admin_client_id=meadowlark_admin_key_1
@admin_client_secret=meadowlark_admin_secret_1

### Authenticate admin
# @name admin1
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "{{admin_client_id}}",
    "client_secret": "{{admin_client_secret}}"
}

###
@admin_token={{admin1.response.body.$.access_token}}
@auth_header_admin_1=Authorization: bearer {{admin1.response.body.$.access_token}}


### Create client1
# @name created_client1
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor"
    ]
}

###
@client1_client_id={{created_client1.response.body.$.client_id}}
@client1_client_secret={{created_client1.response.body.$.client_secret}}

### Authenticate client1
# @name client1
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "{{client1_client_id}}",
    "client_secret": "{{client1_client_secret}}"
}

###
@auth_header=Authorization: bearer {{client1.response.body.$.access_token}}

##### END AUTHENTICATION SETUP

###
POST http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "All Levels",
    "shortDescription": "All Levels",
    "namespace": "uri://ed-fi.org/SchoolCategoryDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/GradeLevelDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "First Grade",
    "shortDescription": "First Grade",
    "namespace": "uri://ed-fi.org/GradeLevelDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

### Create School
# reference-validation: true
# @name school124
POST http://localhost:3000/local/v3.3b/ed-fi/schools
content-type: application/json
{{auth_header}}

{
    "schoolId": 124,
    "nameOfInstitution": "A School",
    "educationOrganizationCategories" : [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
        }
    ],
    "schoolCategories": [
        {
             "schoolCategoryDescriptor": "uri://ed-fi.org/SchoolCategoryDescriptor#All Levels"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
        }
    ]
}

### Atempt to assign School to location - Should succeed
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
{{auth_header}}

{
    "schoolReference":{
        "schoolId": 124
    },
    "classroomIdentificationCode":"Test Assigning School"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/CourseIdentificationSystemDescriptors
content-type: application/json
{{auth_header}}

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "namespace": "uri://ed-fi.org/CourseIdentificationSystemDescriptors"
}

####
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/courses
content-type: application/json
{{auth_header}}

{
    "educationOrganizationReference": {
        "educationOrganizationId": 124
    },
    "courseCode": "1234",
    "courseTitle": "A Course",
    "numberOfParts": 1,
    "identificationCodes": [
        {
            "identificationCode":"testId",
            "courseIdentificationSystemDescriptor":"uri://ed-fi.org/CourseIdentificationSystemDescriptor#Other"
        }
    ]
}
### This delete will fail because the school is referenced by the location and the course
@schoolDocumentlocation = {{school124.response.headers.location}}
# @name schoolDelete
DELETE http://localhost:3000{{schoolDocumentlocation}}
{{auth_header}}

### Blocking uri's were returning an incorrect path, fixed with RND-424
@locationPath = {{schoolDelete.response.body.blockingUris[0]}}
###
@coursePath = {{schoolDelete.response.body.blockingUris[1]}}

### Delete location
DELETE http://localhost:3000{{locationPath}}
{{auth_header}}

### Delete course, if you re-run school delete above it will succeed
DELETE http://localhost:3000{{coursePath}}
{{auth_header}}