##
## Not yet functioning 2022-06-16 
## 


### Authenticate
# @name client1
POST http://localhost:3000/local/api/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

###
@authToken1 = {{client1.response.body.$.access_token}}

#
## Graduation Plans
# Core problem: schoolyear. This may be related to RND-131. The sample payload
# comes straight from the ODS/API 5.3.x. RND-131 alone did not resolve the issue,
# and the new issue is logged in RND-314.
#

###
GET http://localhost:3000/local/v3.3b/ed-fi/graduationPlans
authorization: bearer {{authToken1}}

###
POST http://localhost:3000/local/v3.3b/ed-fi/graduationPlans
authorization: bearer {{authToken1}}
content-type: application/json

{
  "educationOrganizationReference": {
    "educationOrganizationId": 123
  },
  "graduationSchoolYearTypeReference": {
    "schoolYear": 2035
  },
  "graduationPlanTypeDescriptor": "uri://ed-fi.org/GraduationPlanTypeDescriptor#Recommended",
  "totalRequiredCredits": 28
}
