### Set `ACCESS_TOKEN_REQUIRED=true` environment variable before `yarn start:local`
# Be sure to load all descriptors into the database first.


@auth_header_1=Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInN1YiI6InN1cGVyLWdyZWF0LVNJUyIsImp0aSI6IjNkNTliNzVmLWE3NjItNGJhYS05MTE2LTE5YzgyZmRmOGRlMyIsImlhdCI6MTYzNjU2MjA2MCwiZXhwIjozODQ1NTQ4ODgxLCJyb2xlcyI6WyJ2ZW5kb3IiXX0.lUkNIloI8s63UkMK_hlf1iFn0P65hualLPPZcawMQZ4
@auth_header_2=Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInN1YiI6InNtYWxsLXRvd24tc2lzIiwianRpIjoiMGQwZWZmYTctYWExZi00N2E3LTk4NzktNDdhOGJkOWMzMWJiIiwiaWF0IjoxNjM2NTYyMDc5LCJleHAiOjM4NDU1NDg4ODEsInJvbGVzIjpbInZlbmRvciJdfQ.1nTCwqHcUmuUwNBF8Z2NTHqTg8HPN0mWUQ10TqOCEi0


### Try creating a new resource with authorization header - expect success.
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
{{auth_header_1}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Re-POST with different authorization header - expect 403.
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
{{auth_header_2}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Try getting that resource without authorization header - expect 401.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA

### Try getting that resource using the same authorization header that created the record - expect success.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA
{{auth_header_1}}

### Try getting that resource with a different authorization header - expect 403
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA
{{auth_header_2}}

### Try updating that resource using the same authorization header that created the record - expect success.
PUT http://localhost:3000/local/v3.3b/ed-fi/EducationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA
content-type: application/json
{{auth_header_1}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abcdefghijklmnopqrstuvwxyz",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Try updating the resource with wrong authorization header - expect 403
PUT http://localhost:3000/local/v3.3b/ed-fi/EducationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA
content-type: application/json
{{auth_header_2}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Creating a 2nd resource with 2nd authorization header - expect success.
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
{{auth_header_2}}

{
    "contentIdentifier": "second",
    "namespace": "43210",
    "shortDescription": "abcd",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21433"
}

@auth_header_3=Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInJvbGVzIjpbImhvc3QiXSwic3ViIjoidGhlLWJlc3Rlc3Qtc2lzIiwianRpIjoiODI1ZDQ0YjgtYTgxMS00Y2ZmLWJlZjgtY2M4YTY2MTY5YmUwIiwiaWF0IjoxNjU4NTI0MjM1LCJleHAiOjI2NTg1Mjc4MzV9.g5rw2vrcXK29YjAONhlYmqUF13PRYZHbtMYpTFDi0mc
### Get this using the host / FULL_ACCESS authorization - expect success
GET http://localhost:3000/local/v3.3b/ed-fi/EducationContents/1vvBcOeM1WsZkfwgE-edz-dPgkHJY7uyBrEkuQ
{{auth_header_3}}

### Get all resources using the host host token
GET http://localhost:3000/local/v3.3b/ed-fi/EducationContents
{{auth_header_3}}

### Create Resource from token with HOST/FULL_ACCESS authorization - Expect success
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
reference-validation: true
{{auth_header_3}}

{ 
    "studentUniqueId": "s0zf6d1123d3e12",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### Atempt to access the record with an incorrect authorization header - expect 403
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
reference-validation: true
{{auth_header_2}}

{ 
    "studentUniqueId": "s0zf6d1123d3e12",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### Delete Resource with HOST/FULL_ACCESS authorization - Expect success
DELETE http://localhost:3000/local/v3.3b/ed-fi/students/lqojnbvIhjZVo_T-ojp81kjuAC-sjppXmgcZGA
content-type: application/json
reference-validation: true
{{auth_header_3}}


### Query resource using 1st authorization header - expect only 1st record.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/
{{auth_header_1}}

### Query resource using 2nd authorization header - expect only 2nd record.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/
{{auth_header_2}}

### Attempt to retrieve first record in a query using 1st token - expect to receive it
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents?contentIdentifier=first
{{auth_header_1}}


### Attempt to retrieve first record in a query using 2nd token - expect empty array
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents?contentIdentifier=first
{{auth_header_2}}


### Try deleting 1st resource using the wrong authorization header - expect 403
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA
{{auth_header_2}}

### Try deleting 1st resource using the same authorization header that created the record - expect success.
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/YKe0uvuOUdWgG2M086S1i1-o6lg_BmwjFVQyJA
{{auth_header_1}}

### Delete 2nd resource using the same authorization header that created the record - expect success.
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/1vvBcOeM1WsZkfwgE-edz-dPgkHJY7uyBrEkuQ
{{auth_header_2}}


### Add descriptor with first client
POST http://localhost:3000/local/v3.3b/ed-fi/absenceEventCategoryDescriptors
content-type: application/json
{{auth_header_1}}

{
  "codeValue": "Test Client 1",
  "shortDescription": "Test Client 1",
  "namespace": "uri://ed-fi.org/AbsenceEventCategoryDescriptor"
}

### Add descriptor with second client
POST http://localhost:3000/local/v3.3b/ed-fi/absenceEventCategoryDescriptors
content-type: application/json
{{auth_header_2}}

{
  "codeValue": "Test Client 2",
  "shortDescription": "Test Client 2",
  "namespace": "uri://ed-fi.org/AbsenceEventCategoryDescriptor"
}

### Get All AbsenceEventCategory Descriptors - should see both client 1 and client 2, also shows descriptors going to 
### OpenSearch
GET http://localhost:3000/local/v3.3b/ed-fi/absenceEventCategoryDescriptors
content-type: application/json
{{auth_header_3}}