#
# Some of the tests in this file assume that the user has already run throuhg
# the tests in `local.33b.superclass.http`.
#

### Authenticate
# @name client1
POST http://localhost:3000/local/api/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

###
@authToken1 = {{client1.response.body.$.access_token}}

GET http://localhost:3000/local/v3.3b/ed-fi/contentClassDescriptors
authorization: bearer {{authToken1}}

###
# @name contentClassDescriptor
POST http://localhost:3000/local/v3.3b/ed-fi/contentClassDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Presentation",
  "shortDescription": "Presentation",
  "description": "Presentation",
  "namespace": "uri://ed-fi.org/ContentClassDescriptor"
}

###
@contentClassDescriptorLocation = {{contentClassDescriptor.response.headers.location}}
GET http://localhost:3000{{contentClassDescriptorLocation}}
authorization: bearer {{authToken1}}


### Created an EducationContents record
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
authorization: bearer {{authToken1}}

{
    "contentIdentifier": "933zsd4350",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Get all EducationContents records
GET http://localhost:3000/local/v3.3b/ed-fi/EducationContents
authorization: bearer {{authToken1}}

### Get the created record (lower case)
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/rss_5FH6lvpFOUG2AncoHucLzmQugNUejJSXHQ
authorization: bearer {{authToken1}}

### Update the created record
PUT http://localhost:3000/local/v3.3b/ed-fi/educationContents/rss_5FH6lvpFOUG2AncoHucLzmQugNUejJSXHQ
content-type: application/json
authorization: bearer {{authToken1}}

{
    "contentIdentifier": "933zsd4350",
    "namespace": "4321",
    "shortDescription": "abc+",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Delete the created record
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/rss_5FH6lvpFOUG2AncoHucLzmQugNUejJSXHQ
authorization: bearer {{authToken1}}

### 400: Strict validation is enabled, this will fail due to an invalid country
POST http://localhost:3000/local/v3.3b/ed-fi/students
content-type: application/json
authorization: bearer {{authToken1}}
reference-validation: true

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#AD3"
}

### Strict validation is disabled
POST http://localhost:3000/local/v3.3b/ed-fi/students
content-type: application/json
reference-validation: false
authorization: bearer {{authToken1}}

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#AD3"
}


###
DELETE http://localhost:3000/local/v3.3b/ed-fi/students/kKOLuEZJWjsDhpDiJOQlryLw_JBvzQ5KXTF2xg
authorization: bearer {{authToken1}}

###
POST http://localhost:3000/local/v3.3b/ed-fi/countryDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "US",
  "shortDescription": "US",
  "description": "US",
  "namespace": "uri://ed-fi.org/CountryDescriptor"
}

### Now it contains a valid country
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
reference-validation: true
authorization: bearer {{authToken1}}

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### Update this student
PUT http://localhost:3000/local/v3.3b/ed-fi/students/kKOLuEZJWjsDhpDiJOQlryLw_JBvzQ5KXTF2xg
content-type: application/json
reference-validation: false
authorization: bearer {{authToken1}}

{ 
    "studentUniqueId": "s0zf6d1123d3e",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#CA"
}

### Fails with 404 - can't post an abstract entity
POST http://localhost:3000/local/v3.3b/ed-fi/educationOrganizations
content-type: application/json
authorization: bearer {{authToken1}}

{
    "schoolId": 123,
    "categories": [],
    "gradeLevels": []
}

### Fails - note reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations
content-type: application/json
reference-validation: true
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "interventionReference": {
        "interventionIdentificationCode": "111",
        "educationOrganizationId": 123
    }
}

### Succeeds despite intervention code not existing - note reference-validation: false
POST http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations
content-type: application/json
reference-validation: false
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "interventionReference": {
        "interventionIdentificationCode": "111",
        "educationOrganizationId": 123
    }
}


#### Strict validation is off
POST http://localhost:3000/local/v3.3b/ed-fi/sections
content-type: application/json
reference-validation: false
authorization: bearer {{authToken1}}

{ 
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z2"
            }
        }
    ]
}

### Create a location - school does not exist.
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
authorization: bearer {{authToken1}}
reference-validation: true

{
  "classroomIdentificationCode": "string",
  "schoolReference": {
    "schoolId": 99
  },
  "maximumNumberOfSeats": 20,
  "optimalNumberOfSeats": 10
}

### Now the school _does_ exist
POST http://localhost:3000/local/v3.3b/ed-fi/locations
content-type: application/json
reference-validation: true
authorization: bearer {{authToken1}}

{
  "classroomIdentificationCode": "string",
  "schoolReference": {
    "schoolId": 123
  },
  "maximumNumberOfSeats": 20,
  "optimalNumberOfSeats": 10
}

### Term, for supporting the session below
POST http://localhost:3000/local/v3.3b/ed-fi/termDescriptors
content-type: application/json
authorization: bearer {{authToken1}}

{
  "codeValue": "Spring Semester",
  "shortDescription": "Spring Semester",
  "namespace": "uri://ed-fi.org/TermDescriptor"
}

### Create a Session
### This will fail until RND-314 is resolved
POST http://localhost:3000/local/v3.3b/ed-fi/sessions
content-type: application/json
authorization: bearer {{authToken1}}
descriptor-validation: true

{
  "sessionName": "d",
  "schoolYearTypeReference": {
    "schoolYear": 2034
  },
  "beginDate": "2021-01-01",
  "endDate": "2021-06-01",
  "termDescriptor": "uri://ed-fi.org/TermDescriptor#Spring Semester",
  "totalInstructionalDays": 90,
  "schoolReference": {
    "schoolId": 123
  }
}

### Create a course
POST http://localhost:3000/local/v3.3b/ed-fi/courses
content-type: application/json
reference-validation: true
authorization: bearer {{authToken1}}

{
    "courseCode": "span-101",
    "educationOrganizationReference": {
      "educationOrganizationId": 123
    },
    "courseTitle": "Spanish 101",
    "numberOfParts": 1,
    "identificationCodes": []
}

### Create a courseOffering
POST http://localhost:3000/local/v3.3b/ed-fi/courseOfferings
content-type: application/json
reference-validation: true
authorization: bearer {{authToken1}}

{
  "localCourseCode": "abfdddcde",
  "schoolReference": {
    "schoolId": 123
  },
  "sessionReference": {
    "sessionName": "d",
    "schoolId": 123,
    "schoolYear": 2034
  },
  "courseReference": {
    "courseCode": "span-101",
    "educationOrganizationId": 123
  }
}

### Create a section that references that courseOffering. Should cause deletion to fail
POST http://localhost:3000/local/v3.3b/ed-fi/sections
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
      "localCourseCode": "abfdddcde",
      "schoolId": 123,
      "schoolYear": 2034,
      "sessionName": "d"
    },
    "locationReference": {
      "classroomIdentificationCode": "string",
      "schoolId": 123
    }
}

### Should fail due to the presence of the section above
DELETE http://localhost:3000/local/v3.3b/ed-fi/courseOfferings/-epMUEx3z2sXHsjmOtmXdfHZMmggxbj_9sL6TA
authorization: bearer {{authToken1}}

### If the above failed, now try deleting the section and then run above again. Should work now
DELETE http://localhost:3000/local/v3.3b/ed-fi/sections/txtK94BT9QZfS-OhuJzbZa5WFcDcXKqhAOBwFw
authorization: bearer {{authToken1}}

######## List all with GET
GET http://localhost:3000/local/v3.3b/ed-fi/StudentEducationOrganizationAssociations
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/students
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/SexDescriptors
authorization: bearer {{authToken1}}

### Lowercase
GET http://localhost:3000/local/v3.3b/ed-fi/behaviorDescriptors
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/BehaviorDescriptors/41e20a8e3e29596a206ab2eec7118910c7f190ada37148f007357a64
authorization: bearer {{authToken1}}


### 
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencies
content-type: application/json
authorization: bearer {{authToken1}}

{
    "localEducationAgencyId": 2231,
    "nameOfInstitution": "Grand Bend School District",
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent",
    "categories": []
}

####
POST http://localhost:3000/local/v3.3b/ed-fi/Courses
content-type: application/json
authorization: bearer {{authToken1}}

{
    "educationOrganizationReference": {
        "educationOrganizationId": 2231
    },
    "courseCode": "1234",
    "courseTitle": "A Course",
    "numberOfParts": 1,
    "identificationCodes": []
}


####
POST http://localhost:3000/local/v3.3b/ed-fi/StudentEducationOrganizationAssociations
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 2231
    },
    "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Female"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/GradeLevelDescriptors
content-type: application/application/json
authorization: bearer {{authToken1}}

{
  "codeValue": "10",
  "shortDescription": "10",
  "description": "10",
  "namespace": "uri://ed-fi.org/GradeLevelDescriptor"
}


####
POST http://localhost:3000/local/v3.3b/ed-fi/studentSchoolAssociations
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "schoolReference": {
        "schoolId": 123
    },
    "entryDate": "2020-01-01",
    "entryGradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#10"
}

######## GET by ID
GET http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations/gypI96NaEU6Aat_Eg14MTK8rXKo7JGIyDzeIHQ
authorization: bearer {{authToken1}}


###### GET Query
GET http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations?interventionReference.interventionIdentificationCode=111
authorization: bearer {{authToken1}}


### Entity does not exist
GET http://localhost:3000/local/v3.3b/ed-fi/SacademicWeeks
authorization: bearer {{authToken1}}

### Descriptor does not exist
GET http://localhost:3000/local/v3.3b/ed-fi/b3haviorDescriptors
authorization: bearer {{authToken1}}


###
GET http://localhost:3000/local/v3.3b/ed-fi/GeneralStudentProgramAssociations
authorization: bearer {{authToken1}}

### This test covers the scenario previously seen in RND-149
POST http://localhost:3000/local/v3.3b/ed-fi/accounts
content-type: application/json
reference-validation: false
authorization: bearer {{authToken1}}

{
    "educationOrganizationReference": {
      "educationOrganizationId": 255901
    },
    "accountIdentifier": "1.200.100.10001",
    "fiscalYear": 2012,
    "accountName": "RegularInstructionsss",
    "accountCodes": [
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "100"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "101"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "102"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "103"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "104"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "105"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "106"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "107"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "108"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "109"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "110"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "111"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "112"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "113"
        }
      }
    ]
}

### delete the record above
DELETE http://localhost:3000/local/v3.3b/ed-fi/accounts/gyGSt9yVSJdYUxgdOemhBBWjyIa9f1sA5uOZaA
authorization: bearer {{authToken1}}


###
# Limit/Offset/TotalCount Testing: ODS/API supports query parameters "limit", "offset", and "totalcount" for special
# purposes. Meadowlark does not yet support these values. The following queries should all return 200,
# thus indicating that the three terms are ignored.
GET http://localhost:3000/local/v3.3b/ed-fi/students/?limit=1&offset=2&totalCount=true
authorization: bearer {{authToken1}}


### A simple DELETE validation test
# Try deleting a descriptor that is used by a school
# !!! Currently this will succeed (which is not good) AND crash the application. RND-296
DELETE http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors/gPVEJ4PgrhnDa-eMNdqix4aoE8oeVAt8E9opyQ
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors/gPVEJ4PgrhnDa-eMNdqix4aoE8oeVAt8E9opyQ
authorization: bearer {{authToken1}}


### Try to delete school 123. Should be denied (409) because there are references to it
DELETE http://localhost:3000/local/v3.3b/ed-fi/Schools/L9gXuk9vioIoG64QKp8NFO2f3AOe78fV-HrtfQ
authorization: bearer {{authToken1}}


### Issue covered by RND-297
POST http://localhost:3000/local/v3.3b/ed-fi/parents
authorization: bearer {{authToken1}}
content-type: application/json

{
  "parentUniqueId": "778791",
  "firstName": "Arthur",
  "lastSurname": "Woods",
  "personalTitlePrefix": "Mr",
  "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Male",
  "electronicMails": [],
  "internationalAddresses": [],
  "languages": [],
  "otherNames": [],
  "addresses": [
    {
      "addressTypeDescriptor": "uri://ed-fi.org/AddressTypeDescriptor#Home",
      "city": "Grand Bend",
      "postalCode": "78834",
      "stateAbbreviationDescriptor": "uri://ed-fi.org/StateAbbreviationDescriptor#TX",
      "streetNumberName": "54 Rocky Clarendon Avenue",
      "nameOfCounty": "WILLISTON",
      "periods": []
    }
  ],
  "telephones": [
    {
      "telephoneNumber": "(950) 959 3641",
      "telephoneNumberTypeDescriptor": "uri://ed-fi.org/TelephoneNumberTypeDescriptor#Other",
      "orderOfPriority": 1
    }
  ]
}


### Issue covered by RND-298
POST http://localhost:3000/local/v3.3b/ed-fi/communityOrganizations
authorization: bearer {{authToken1}}
content-type: application/json


{
    "communityOrganizationId": 19,
    "nameOfInstitution": "Communities in Schools",
    "shortNameOfInstitution": "CIS",
    "addresses": [],
    "categories": [
      {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
      }
    ],
    "identificationCodes": [
      {
        "educationOrganizationIdentificationSystemDescriptor": "uri://ed-fi.org/EducationOrganizationIdentificationSystemDescriptor#SEA",
        "identificationCode": "19"
      }
    ],
    "indicators": [],
    "institutionTelephones": [],
    "internationalAddresses": []
}
