### Authenticate as a non-admin
# @name client1
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

###
@auth_header_client_1=Authorization: bearer {{client1.response.body.$.access_token}}


#################### POST authorization client


### Try creating client as a non-admin, should 403 Forbidden
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_client_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor",
        "assessment"
    ]
}

### Try creating client with a bad token, should 403 Forbidden
POST http://localhost:3000/local/oauth/client
content-type: application/json
Authorization: bearer Not-A-Token

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor",
        "assessment"
    ]
}


### Authenticate as an admin
# @name admin1
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_admin_key_1",
    "client_secret": "meadowlark_admin_secret_1"
}

###
@auth_header_admin_1=Authorization: bearer {{admin1.response.body.$.access_token}}


### Create client as an admin, should succeed
# @name client1
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor"
    ]
}

### Create client with additional assessment role, should succeed
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor",
        "assessment"
    ]
}

### Send request body with empty body, should fail with 400 Bad Request
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{}

### Send request body without roles, should fail with 400 Bad Request
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS"
}

### Send request body with invalid role, should fail with 400 Bad Request
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "not vendor"
    ]
}

### Create client with one valid, one invalid role, should fail with 400 Bad Request
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor",
        "not assessment"
    ]
}

### Send request body with only assessment role, should fail with 400 Bad Request
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "assessment"
    ]
}


#################### PUT authorization client

###
@created_client_id_1={{client1.response.body.$.client_id}}

### Update client as an admin, should succeed
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor"
    ]
}


### Update with non-existent client id, should 404
PUT http://localhost:3000/local/oauth/client/11111111-1111-1111-1111-111111111111
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor"
    ]
}


### Update client with additional assessment role, should succeed
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor",
        "assessment"
    ]
}

### Send request body with empty body, should fail with 400 Bad Request
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{}

### Send request body without roles, should fail with 400 Bad Request
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS"
}

### Send request body with invalid role, should fail with 400 Bad Request
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "not vendor"
    ]
}

### Create client with one valid, one invalid role, should fail with 400 Bad Request
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "vendor",
        "not assessment"
    ]
}

### Send request body with only assessment role, should fail with 400 Bad Request
PUT http://localhost:3000/local/oauth/client/{{created_client_id_1}}
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Hometown SIS",
    "roles": [
        "assessment"
    ]
}

#################### Request bearer token


### Authenticate as a hardcoded non-admin, form url encoded, should succeed
POST http://localhost:3000/local/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=meadowlark_key_1&client_secret=meadowlark_secret_1

###

@created_client_secret_1={{client1.response.body.$.client_secret}}

### Authenticate as a previously created client, form url encoded, should succeed
# @name newClient
POST http://localhost:3000/local/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{created_client_id_1}}&client_secret={{created_client_secret_1}}

###
@newClientToken = {{newClient.response.body.$.access_token}}

### Use the new client's token
GET http://localhost:3000/local/v3.3b/ed-fi/contentClassDescriptors
authorization: bearer {{newClientToken}}

### Authenticate as a previously created client with wrong secret, form url encoded, should 401
POST http://localhost:3000/local/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{created_client_id_1}}&client_secret=bad_secret

### Create client as an admin, should succeed
# @name client2
POST http://localhost:3000/local/oauth/client
content-type: application/json
{{auth_header_admin_1}}

{
    "clientName": "Totally new SIS",
    "roles": [
        "vendor"
    ]
}
###

@created_client_id_2={{client2.response.body.$.client_id}}
#fastify.post(`/${stage}/oauth/client/:clientId/reset`, updateAuthorizationClientHandler);
### 
POST http://localhost:3000/local/oauth/client/{{created_client_id_2}}/reset
content-type: application/json
{{auth_header_admin_1}}