#
# SIGNING KEY
#

### Generate a signing key. Save to .env as 
# SIGNING_KEY=<paste here>
GET http://localhost:3000/local/createKey

#
# AUTHENTICATE
#

### should succeed, vendor 1 (JSON)
POST http://localhost:3000/local/api/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

### should succeed, vendor 1 (form encoded)
POST http://localhost:3000/local/api/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=meadowlark_key_1
&client_secret=meadowlark_secret_1

### should succeed, vendor 1 (form encoded, alternate using basic auth)
# @name client1
POST http://localhost:3000/local/api/oauth/token
content-type: application/x-www-form-urlencoded
authorization: Basic bWVhZG93bGFya19rZXlfMTptZWFkb3dsYXJrX3NlY3JldF8x

grant_type=client_credentials


### should succeed, vendor 2
# @name client2
POST http://localhost:3000/local/api/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=meadowlark_key_2
&client_secret=meadowlark_secret_2

### mix & match - should fail - expect 401
POST http://localhost:3000/local/api/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=meadowlark_key_1
&client_secret=meadowlark_secret_2

### completely bogus - should fail - expect 401
POST http://localhost:3000/local/api/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=meadowlark_key_1_bogus
&client_secret=meadowlark_secret_1_bogus


### should succeed, client 3 with host access
# @name host_client
POST http://localhost:3000/local/api/oauth/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=meadowlark_key_3
&client_secret=meadowlark_secret_3

###
@hostToken = {{host_client.response.body.$.access_token}}


#
# VERIFY
#

### An expired token
GET http://localhost:3000/local/verify
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInN1YiI6InN1cGVyLWdyZWF0LVNJUyIsImNsaWVudF9pZCI6ImMzVndaWEl0WjNKbFlYUXRVMGxUIiwianRpIjoiZjQ2OTYyYjQtMzg4NS00Y2JiLWE4YjktMmY5NTY5OGNkM2U1IiwiaWF0IjoxNjU1MjQ0OTE3LCJleHAiOjE3MTg0MDF9.iuIAVDeszM_f-yzqylY65zim87WJtau-0HQUj30x66U

### Vendor 1 token
@authToken1 = {{client1.response.body.$.access_token}}

GET http://localhost:3000/local/verify
Authorization: bearer {{authToken1}}

### Vendor 2 token
@authToken2 = {{client2.response.body.$.access_token}}

GET http://localhost:3000/local/verify
Authorization: bearer {{authToken2}}

### Test a token that has been tampered with by changing the subject - expect 400
GET http://localhost:3000/local/verify
Authorization: bearer a{{authToken2}}

### Gibberish token - expect 400
GET http://localhost:3000/local/verify
Authorization: bearer gibberish

### No token - expect 401
GET http://localhost:3000/local/verify
Authorization: bearer 

### Host Token - Should return FULL_ACCESS auth
GET http://localhost:3000/local/verify
Authorization: bearer {{hostToken}}

### Missing roles should return invalid_token - Roles are missing or roles are invalid on token
GET http://localhost:3000/local/verify
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlZC1maS1tZWFkb3dsYXJrIiwiYXVkIjoibWVhZG93bGFyayIsInN1YiI6InN1cGVyLWdyZWF0LVNJUyIsImp0aSI6IjgyNWQ0NGI4LWE4MTEtNGNmZi1iZWY4LWNjOGE2NjE2OWJlMCIsImNsaWVudF9pZCI6ImMzVndaWEl0WjNKbFlYUXRVMGxUIiwiaWF0IjoxNjU4NTI0MjM1LCJleHAiOjI2NTg1Mjc4MzV9.nj2ajxWjv0Vfqrx9200xVOds_hiOMPXcf6I0dYTkw_M

#
# POST (Requires ACCESS_TOKEN_REQUIRED=true environment variable)
#

### Student owned by Vendor 1
POST http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
Authorization: bearer {{authToken1}}

{ 
    "studentUniqueId": "1",
    "firstName": "Vendor",
    "lastSurname": "One",
    "birthDate": "2001-01-01"
}

### Student owned by Vendor 2
POST http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
Authorization: bearer {{authToken2}}

{ 
    "studentUniqueId": "2",
    "firstName": "Vendor",
    "lastSurname": "Two",
    "birthDate": "2002-02-02"
}

### Vendor 1 attempts to POST on top of Vendor 2 Student - this is delegated to PUT under the covers - should fail - expect 404
POST http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
Authorization: bearer {{authToken1}}

{ 
    "studentUniqueId": "2",
    "firstName": "Vendor",
    "lastSurname": "Two",
    "birthDate": "2002-02-02"
}

#
# GET by id (Requires ACCESS_TOKEN_REQUIRED=true environment variable)
#

### Vendor 1 GET of Student owned by Vendor 1
GET http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122-E_3xsQrCBCmNqUBDPLyfA
Authorization: bearer {{authToken1}}

### Vendor 1 GET of Student owned by Vendor 2 - should fail - expect 404
GET http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122fEjh3kkivOq7W7vskq0EcQ
Authorization: bearer {{authToken1}}

### Vendor 2 GET of Student owned by Vendor 2
GET http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122fEjh3kkivOq7W7vskq0EcQ
Authorization: bearer {{authToken2}}

### Vendor 2 GET of Student owned by Vendor 1 - should fail - expect 404
GET http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122-E_3xsQrCBCmNqUBDPLyfA
Authorization: bearer {{authToken2}}

#
# PUT by id (Requires ACCESS_TOKEN_REQUIRED=true environment variable)
#

### Vendor 2 PUT for Student owned by Vendor 2
PUT http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122fEjh3kkivOq7W7vskq0EcQ
content-type: application/json
Authorization: bearer {{authToken2}}

{ 
    "studentUniqueId": "2",
    "firstName": "Vendor",
    "lastSurname": "Two - Updated",
    "birthDate": "2002-02-02"
}

### Vendor 1 attempts to PUT on top of Vendor 2 Student - should fail - expect 404
PUT http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122fEjh3kkivOq7W7vskq0EcQ
content-type: application/json
Authorization: bearer {{authToken1}}

{ 
    "studentUniqueId": "2",
    "firstName": "Vendor",
    "lastSurname": "Two - Updated",
    "birthDate": "2002-02-02"
}

#
# DELETE by id (Requires ACCESS_TOKEN_REQUIRED=true environment variable)
#

### Vendor 1 DELETE of Student owned by Vendor 1
DELETE http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122-E_3xsQrCBCmNqUBDPLyfA
Authorization: bearer {{authToken1}}

### Vendor 1 DELETE of Student owned by Vendor 2 - should fail - expect 404
DELETE http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M80122fEjh3kkivOq7W7vskq0EcQ
Authorization: bearer {{authToken1}}
