
### Create a course
POST http://localhost:3000/local/v3.3b/ed-fi/courses
content-type: application/json
authorization: bearer {{authToken1}}

{
    "courseCode": "span-101",
    "educationOrganizationReference": {
      "educationOrganizationId": 123
    },
    "courseTitle": "Spanish 101",
    "numberOfParts": 1,
    "identificationCodes": [
      {
        "identificationCode": "string",
        "courseIdentificationSystemDescriptor": "string"
      }
    ]
}

### School year is not supported - expected 404
POST http://localhost:3000/local/v3.3b/ed-fi/schoolYearTypes
content-type: application/json
authorization: bearer {{authToken1}}

{
  "schoolYear": 2034,
  "currentSchoolYear": false
}


### Create a courseOffering
# @name courseOffering
POST http://localhost:3000/local/v3.3b/ed-fi/courseOfferings
content-type: application/json
authorization: bearer {{authToken1}}

{
  "localCourseCode": "abfdddcde",
  "schoolReference": {
    "schoolId": 123
  },
  "sessionReference": {
    "sessionName": "d",
    "schoolId": 123,
    "schoolYear": 2034
  },
  "courseReference": {
    "courseCode": "span-101",
    "educationOrganizationId": 123
  }
}

### Create a section that references that courseOffering. Should cause deletion to fail
# @name section
POST http://localhost:3000/local/v3.3b/ed-fi/sections
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
      "localCourseCode": "abfdddcde",
      "schoolId": 123,
      "schoolYear": 2034,
      "sessionName": "d"
    },
    "locationReference": {
      "classroomIdentificationCode": "string",
      "schoolId": 123
    }
}

### Should fail due to the presence of the section above
DELETE http://localhost:3000{{courseOffering.response.headers.location}}
authorization: bearer {{authToken1}}

### If the above failed, now try deleting the section and then run above again. Should work now
DELETE http://localhost:3000{{section.response.headers.location}}
authorization: bearer {{authToken1}}

######## List all with GET
GET http://localhost:3000/local/v3.3b/ed-fi/StudentEducationOrganizationAssociations
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/students
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/SexDescriptors
authorization: bearer {{authToken1}}

### Lowercase
GET http://localhost:3000/local/v3.3b/ed-fi/behaviorDescriptors
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/behaviorDescriptors/fCqNHqFd1j9tNzZ6lDcSxuwX2ZvS2IcCnyU-hg
authorization: bearer {{authToken1}}

### Create an EducationOrganizationCategory descriptor
POST http://localhost:3000/local/v3.3b/ed-fi/educationOrganizationCategoryDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "description": "Other",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

### Create an LocalEducationAgencyCategory descriptor
POST http://localhost:3000/local/v3.3b/ed-fi/localEducationAgencyCategoryDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
    "codeValue": "Independent",
    "shortDescription": "Independent",
    "description": "Independent",
    "namespace": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor"
}


### 
POST http://localhost:3000/local/v3.3b/ed-fi/LocalEducationAgencies
content-type: application/json
authorization: bearer {{authToken1}}

{
    "localEducationAgencyId": 2231,
    "nameOfInstitution": "Grand Bend School District",
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Independent",
    "categories": [
      {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
      }
    ]
}

####
POST http://localhost:3000/local/v3.3b/ed-fi/Courses
content-type: application/json
authorization: bearer {{authToken1}}

{
    "educationOrganizationReference": {
        "educationOrganizationId": 2231
    },
    "courseCode": "1234",
    "courseTitle": "A Course",
    "numberOfParts": 1,
    "identificationCodes": [
      {
        "identificationCode": "string",
        "courseIdentificationSystemDescriptor": "string"
      }
    ]
}

### Create a Sex descriptor
POST http://localhost:3000/local/v3.3b/ed-fi/sexDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
    "codeValue": "Female",
    "shortDescription": "Female",
    "description": "Female",
    "namespace": "uri://ed-fi.org/SexDescriptor"
}

####
POST http://localhost:3000/local/v3.3b/ed-fi/StudentEducationOrganizationAssociations
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 2231
    },
    "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Female"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/GradeLevelDescriptors
content-type: application/application/json
authorization: bearer {{authToken1}}

{
  "codeValue": "10",
  "shortDescription": "10",
  "description": "10",
  "namespace": "uri://ed-fi.org/GradeLevelDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/GraduationPlanTypeDescriptors
content-type: application/application/json
authorization: bearer {{authToken1}}

{
  "codeValue": "Minimum",
  "shortDescription": "Minimum",
  "description": "Minimum",
  "namespace": "uri://ed-fi.org/GraduationPlanTypeDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/graduationPlans
content-type: application/json
authorization: bearer {{authToken1}}

{ 
  "educationOrganizationReference": {
    "educationOrganizationId": 123
  },
  "graduationPlanTypeDescriptor": "uri://ed-fi.org/GraduationPlanTypeDescriptor#Minimum",
  "graduationSchoolYearTypeReference": {
    "schoolYear": 2024
  },
  "totalRequiredCredits": 100
}

###
GET http://localhost:3000/local/v3.3b/ed-fi/graduationPlans
content-type: application/json
authorization: bearer {{authToken1}}

#### Contains two different school years
POST http://localhost:3000/local/v3.3b/ed-fi/studentSchoolAssociations
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "schoolReference": {
        "schoolId": 123
    },
    "entryDate": "2020-01-01",
    "entryGradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#10",
    "classOfSchoolYearTypeReference": {
      "schoolYear": 2022
    },
    "schoolYearTypeReference": {
      "schoolYear": 2023
    }
}

#### Contains two INVALID school years
PUT http://localhost:3000/local/v3.3b/ed-fi/studentSchoolAssociations
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "schoolReference": {
        "schoolId": 123
    },
    "entryDate": "2020-01-01",
    "entryGradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#10",
    "classOfSchoolYearTypeReference": {
      "schoolYear": 202
    },
    "schoolYearTypeReference": {
      "schoolYear": 203
    }
}

### This fails, documented in RND-426
PUT http://localhost:3000/local/v3.3b/ed-fi/studentSchoolAssociations/uJ8Rk-JjLZuoSnnSQUUuG2-LY9kz5QrrD0_UyQ
content-type: application/json
authorization: bearer {{authToken1}}

{ 
    "studentReference": {
        "studentUniqueId": "s0zf6d1123d3e"
    },
    "schoolReference": {
        "schoolId": 123
    },
    "entryDate": "2020-01-01",
    "entryGradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#10",
    "classOfSchoolYearTypeReference": {
      "schoolYear": 2022
    },
    "schoolYearTypeReference": {
      "schoolYear": 2023
    },
    "graduationPlanReference": {
      "educationOrganizationId": 123,
      "graduationPlanTypeDescriptor": "uri://ed-fi.org/GraduationPlanTypeDescriptor#Minimum",
      "graduationSchoolYear": 2024
    }
}


######## GET by ID
GET http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations/KbK3nYKOeuNj1aASuMm2IlM3nTtcvlVfDLTSeg
authorization: bearer {{authToken1}}


###### GET Query
GET http://localhost:3000/local/v3.3b/ed-fi/StudentInterventionAssociations?interventionIdentificationCode=111
authorization: bearer {{authToken1}}


### Entity does not exist
GET http://localhost:3000/local/v3.3b/ed-fi/SacademicWeeks
authorization: bearer {{authToken1}}

### Descriptor does not exist
GET http://localhost:3000/local/v3.3b/ed-fi/b3haviorDescriptors
authorization: bearer {{authToken1}}


###
GET http://localhost:3000/local/v3.3b/ed-fi/GeneralStudentProgramAssociations
authorization: bearer {{authToken1}}

### This test covers the scenario previously seen in RND-149
# reference-validation: false
POST http://localhost:3000/local/v3.3b/ed-fi/accounts
content-type: application/json
authorization: bearer {{authToken4}}

{
    "educationOrganizationReference": {
      "educationOrganizationId": 255901
    },
    "accountIdentifier": "1.200.100.10001",
    "fiscalYear": 2012,
    "accountName": "RegularInstructionsss",
    "accountCodes": [
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "100"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "101"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "102"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "103"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "104"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "105"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "106"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "107"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "108"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "109"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "110"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "111"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "112"
        }
      },
      {
        "accountCodeReference": {
          "educationOrganizationId": 255901,
          "fiscalYear": 2011,
          "accountClassificationDescriptor": "uri://ed-fi.org/AccountClassificationDescriptor#Object",
          "accountCodeNumber": "113"
        }
      }
    ]
}

### delete the record above
DELETE http://localhost:3000/local/v3.3b/ed-fi/accounts/maSXphjSRux6PX3WbbQKovXlVJEmso06cecAZw
authorization: bearer {{authToken1}}


###
# Limit/Offset/TotalCount Testing: ODS/API supports query parameters "limit", "offset", and "totalcount" for special
# purposes. Meadowlark does not yet support these values. The following queries should all return 200,
# thus indicating that the three terms are ignored.
GET http://localhost:3000/local/v3.3b/ed-fi/students/?limit=1&offset=2&totalCount=true
authorization: bearer {{authToken1}}


###
DELETE http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors/gPVEJ4PgrhnDa-eMNdqix4aoE8oeVAt8E9opyQ
authorization: bearer {{authToken1}}

###
GET http://localhost:3000/local/v3.3b/ed-fi/SchoolCategoryDescriptors/gPVEJ4PgrhnDa-eMNdqix4aoE8oeVAt8E9opyQ
authorization: bearer {{authToken1}}


### Try to delete school 123. Should be denied (409) because there are references to it. Solved in RND-327.
DELETE http://localhost:3000/local/v3.3b/ed-fi/Schools/LZRuhjvR1UiLz9Tat_4HOBmlPt_xB_pA20fKyQ
authorization: bearer {{authToken1}}


### Create a parent. Solved in RND-298.
POST http://localhost:3000/local/v3.3b/ed-fi/parents
authorization: bearer {{authToken1}}
content-type: application/json

{
  "parentUniqueId": "778791",
  "firstName": "Arthur",
  "lastSurname": "Woods",
  "personalTitlePrefix": "Mr",
  "sexDescriptor": "uri://ed-fi.org/SexDescriptor#Female",
  "electronicMails": [],
  "internationalAddresses": [],
  "languages": [],
  "otherNames": [],
  "addresses": [
    {
      "addressTypeDescriptor": "uri://ed-fi.org/AddressTypeDescriptor#Home",
      "city": "Grand Bend",
      "postalCode": "78834",
      "stateAbbreviationDescriptor": "uri://ed-fi.org/StateAbbreviationDescriptor#TX",
      "streetNumberName": "54 Rocky Clarendon Avenue",
      "nameOfCounty": "WILLISTON",
      "periods": []
    }
  ],
  "telephones": [
    {
      "telephoneNumber": "(950) 959 3641",
      "telephoneNumberTypeDescriptor": "uri://ed-fi.org/TelephoneNumberTypeDescriptor#Other",
      "orderOfPriority": 1
    }
  ]
}


### Create a community organization. Solved in RND-298.
POST http://localhost:3000/local/v3.3b/ed-fi/communityOrganizations
authorization: bearer {{authToken1}}
content-type: application/json


{
    "communityOrganizationId": 19,
    "nameOfInstitution": "Communities in Schools",
    "shortNameOfInstitution": "CIS",
    "addresses": [],
    "categories": [
      {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
      }
    ],
    "identificationCodes": [
      {
        "educationOrganizationIdentificationSystemDescriptor": "uri://ed-fi.org/EducationOrganizationIdentificationSystemDescriptor#SEA",
        "identificationCode": "19"
      }
    ]
}



#
## PostSecondaryInstitutions
#


###
POST http://localhost:3000/local/v3.3b/ed-fi/OperationalStatusDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Active",
  "description": "Active",
  "shortDescription": "Active",
  "namespace": "uri://ed-fi.org/OperationalStatusDescriptor"
}
###
POST http://localhost:3000/local/v3.3b/ed-fi/PostSecondaryInstitutionLevelDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Four or more years",
  "description": "Four or more years",
  "shortDescription": "Four or more years",
  "namespace": "uri://ed-fi.org/PostSecondaryInstitutionLevelDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Post Secondary Institution",
  "description": "Post Secondary Institution",
  "shortDescription": "Post Secondary Institution",
  "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/postSecondaryInstitutions
authorization: bearer {{authToken1}}
content-type: application/json

{
    "postSecondaryInstitutionId": 6000203,
    "nameOfInstitution": "The University of Texas at Austin",
    "operationalStatusDescriptor": "uri://ed-fi.org/OperationalStatusDescriptor#Active",
    "shortNameOfInstitution": "UT-Austin",
    "webSite": "https://www.utexas.edu/",
    "postSecondaryInstitutionLevelDescriptor": "uri://ed-fi.org/PostSecondaryInstitutionLevelDescriptor#Four or more years",
    "addresses": [],
    "categories": [
        {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Post Secondary Institution"
        }
    ],
    "identificationCodes": [],
    "indicators": [],
    "institutionTelephones": [
        {
        "institutionTelephoneNumberTypeDescriptor": "uri://ed-fi.org/InstitutionTelephoneNumberTypeDescriptor#Main",
        "telephoneNumber": "(512) 471-3434"
        }
    ],
    "internationalAddresses": [],
    "mediumOfInstructions": []
}


#
## EducationServiceCenters
#

###
POST http://localhost:3000/local/v3.3b/ed-fi/EducationOrganizationCategoryDescriptors
authorization: bearer {{authToken1}}
content-type: application/json

{
  "codeValue": "Education Service Center",
  "shortDescription": "Education Service Center",
  "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}

###
POST http://localhost:3000/local/v3.3b/ed-fi/educationServiceCenters
authorization: bearer {{authToken1}}
content-type: application/json

{
    "educationServiceCenterId": 255950,
    "nameOfInstitution": "Region 99 Education Service Center",
    "addresses": [
      {
        "addressTypeDescriptor": "uri://ed-fi.org/AddressTypeDescriptor#Mailing",
        "city": "Dallas",
        "postalCode": "75217",
        "stateAbbreviationDescriptor": "uri://ed-fi.org/StateAbbreviationDescriptor#TX",
        "streetNumberName": "P.O. Box 898",
        "nameOfCounty": "Dallas",
        "periods": []
      },
      {
        "addressTypeDescriptor": "uri://ed-fi.org/AddressTypeDescriptor#Physical",
        "city": "Dallas",
        "postalCode": "75217",
        "stateAbbreviationDescriptor": "uri://ed-fi.org/StateAbbreviationDescriptor#TX",
        "streetNumberName": "898 Texas Education Blvd.",
        "nameOfCounty": "Dallas",
        "periods": []
      }
    ],
    "categories": [
      {
        "educationOrganizationCategoryDescriptor": 
          "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Education Service Center"
      }
    ],
    "identificationCodes": [
      {
        "educationOrganizationIdentificationSystemDescriptor": 
          "uri://ed-fi.org/EducationOrganizationIdentificationSystemDescriptor#NCES",
        "identificationCode": "255950"
      }
    ],
    "indicators": [],
    "institutionTelephones": [
      {
        "institutionTelephoneNumberTypeDescriptor": "uri://ed-fi.org/InstitutionTelephoneNumberTypeDescriptor#Fax",
        "telephoneNumber": "(214) 876-8921"
      },
      {
        "institutionTelephoneNumberTypeDescriptor": "uri://ed-fi.org/InstitutionTelephoneNumberTypeDescriptor#Main",
        "telephoneNumber": "(214) 876-8290"
      }
    ],
    "internationalAddresses": []
  }