### Set `ACCESS_TOKEN_REQUIRED=true` environment variable before `yarn start:local`
# Be sure to load all descriptors into the database first.

### Authenticate
# @name client1
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}
###
@auth_header_1=Authorization: bearer {{client1.response.body.$.access_token}}
###
# @name client2
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_2",
    "client_secret": "meadowlark_secret_2"
}
###
@auth_header_2=Authorization: bearer {{client2.response.body.$.access_token}}
###
# @name client3
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_3",
    "client_secret": "meadowlark_secret_3"
}
###
@auth_header_3=Authorization: bearer {{client3.response.body.$.access_token}}

### Try creating a new resource with authorization header - expect success.
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
{{auth_header_1}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Re-POST with different authorization header - expect 403.
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
{{auth_header_2}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Try getting that resource without authorization header - expect 401.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ

### Try getting that resource using the same authorization header that created the record - expect success.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ
{{auth_header_1}}

### Try getting that resource with a different authorization header - expect 403
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ
{{auth_header_2}}

### Try updating that resource using the same authorization header that created the record - expect success.
PUT http://localhost:3000/local/v3.3b/ed-fi/EducationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ
content-type: application/json
{{auth_header_1}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abcdefghijklmnopqrstuvwxyz",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Try updating the resource with wrong authorization header - expect 403
PUT http://localhost:3000/local/v3.3b/ed-fi/EducationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ
content-type: application/json
{{auth_header_2}}

{
    "contentIdentifier": "first",
    "namespace": "4321",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "2143"
}

### Creating a 2nd resource with 2nd authorization header - expect success.
POST http://localhost:3000/local/v3.3b/ed-fi/EducationContents
content-type: application/json
{{auth_header_2}}

{
    "contentIdentifier": "second",
    "namespace": "43210",
    "shortDescription": "abcd",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21433"
}

### Get this using the host / FULL_ACCESS authorization - expect success
GET http://localhost:3000/local/v3.3b/ed-fi/EducationContents/c4ak9D7jEwS-MCAYiY-urPsWWs0lJp7PH8I-5w
{{auth_header_3}}

### Get all resources using the host host token
GET http://localhost:3000/local/v3.3b/ed-fi/EducationContents
{{auth_header_3}}

### Create Resource from token with HOST/FULL_ACCESS authorization - Expect success
# reference-validation: true
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
{{auth_header_3}}

{ 
    "studentUniqueId": "s0zf6d1123d3e12",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### Atempt to access the record with an incorrect authorization header - expect 403
# reference-validation: true
POST  http://localhost:3000/local/v3.3b/ed-fi/students/
content-type: application/json
{{auth_header_2}}

{ 
    "studentUniqueId": "s0zf6d1123d3e12",
    "firstName": "Hello",
    "lastSurname": "World",
    "birthDate": "2001-01-01",
    "birthCountryDescriptor": "uri://ed-fi.org/CountryDescriptor#US"
}

### Delete Resource with HOST/FULL_ACCESS authorization - Expect success
# reference-validation: true
DELETE http://localhost:3000/local/v3.3b/ed-fi/students/WhT14ozRv-M801224CfZEcHrCmTjyLf11mBYrw
content-type: application/json
{{auth_header_3}}


### Query resource using 1st authorization header - expect only 1st record.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/
{{auth_header_1}}

### Query resource using 2nd authorization header - expect only 2nd record.
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents/
{{auth_header_2}}

### Attempt to retrieve first record in a query using 1st token - expect to receive it
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents?contentIdentifier=first
{{auth_header_1}}


### Attempt to retrieve first record in a query using 2nd token - expect empty array
GET http://localhost:3000/local/v3.3b/ed-fi/educationContents?contentIdentifier=first
{{auth_header_2}}


### Try deleting 1st resource using the wrong authorization header - expect 403
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ
{{auth_header_2}}

### Try deleting 1st resource using the same authorization header that created the record - expect success.
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/c4ak9D7jEwS-MCAYBzajOD421Q23lVSGomW5oQ
{{auth_header_1}}

### Delete 2nd resource using the same authorization header that created the record - expect success.
DELETE http://localhost:3000/local/v3.3b/ed-fi/educationContents/c4ak9D7jEwS-MCAYiY-urPsWWs0lJp7PH8I-5w
{{auth_header_2}}


### Add descriptor with first client
POST http://localhost:3000/local/v3.3b/ed-fi/absenceEventCategoryDescriptors
content-type: application/json
{{auth_header_1}}

{
  "codeValue": "Test Client 1",
  "shortDescription": "Test Client 1",
  "namespace": "uri://ed-fi.org/AbsenceEventCategoryDescriptor"
}

### Add descriptor with second client
POST http://localhost:3000/local/v3.3b/ed-fi/absenceEventCategoryDescriptors
content-type: application/json
{{auth_header_2}}

{
  "codeValue": "Test Client 2",
  "shortDescription": "Test Client 2",
  "namespace": "uri://ed-fi.org/AbsenceEventCategoryDescriptor"
}

### Get All AbsenceEventCategory Descriptors - should see both client 1 and client 2, also shows descriptors going to 
### OpenSearch
GET http://localhost:3000/local/v3.3b/ed-fi/absenceEventCategoryDescriptors
content-type: application/json
{{auth_header_3}}