### MetaEd model metadata with GET

### API Version
GET http://localhost:3000/local/

### Metadata - open API resource list

GET http://localhost:3000/local/metadata/

### Metadata - Swagger for resources

GET http://localhost:3000/local/metadata/resources/swagger.json

### Metadata - Swagger for descriptors

GET http://localhost:3000/local/metadata/descriptors/swagger.json

### OAuth token request
POST http://localhost:3000/local/oauth/token
content-type: application/json

{}

### Dependencies
GET http://localhost:3000/local/metadata/data/v3/dependencies