#### These are the manual components of the automated system tests
# @name client1
POST http://localhost:3000/local/oauth/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "meadowlark_key_1",
    "client_secret": "meadowlark_secret_1"
}

###
@auth_header=Authorization: bearer {{client1.response.body.$.access_token}}


### API Version
GET http://localhost:3000/metaed
{{auth_header}}


#################### School

### Create a GradeLevel descriptor
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/gradeLevelDescriptors
{{auth_header}}
content-type: application/json

{
    "codeValue": "First Grade",
    "shortDescription": "First Grade",
    "description": "First Grade",
    "namespace": "uri://ed-fi.org/GradeLevelDescriptor"
}

### Create an EducationOrganizationCategory descriptor
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/educationOrganizationCategoryDescriptors
{{auth_header}}
content-type: application/json

{
    "codeValue": "Other",
    "shortDescription": "Other",
    "description": "Other",
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor"
}


### Create a School record
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/schools
{{auth_header}}
content-type: application/json

{
    "schoolId": 123,
    "gradeLevels": [
      {
          "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
      }
    ],
    "nameOfInstitution": "abc",
    "educationOrganizationCategories": [
      {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
      }
    ]
}

### Get the created record
GET http://localhost:3000/local/v3.3b/ed-fi/schools/LZRuhjvR1UiLz9Tat_4HOBmlPt_xB_pA20fKyQ
{{auth_header}}

### Query the created record
GET http://localhost:3000/local/v3.3b/ed-fi/schools/?nameOfInstitution=abc
{{auth_header}}


### Update the created record
# reference-validation: true
PUT http://localhost:3000/local/v3.3b/ed-fi/schools/LZRuhjvR1UiLz9Tat_4HOBmlPt_xB_pA20fKyQ
{{auth_header}}
content-type: application/json

{
    "schoolId": 123,
    "gradeLevels": [
      {
          "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#First Grade"
      }
    ],
    "nameOfInstitution": "abc*****",
    "educationOrganizationCategories": [
      {
        "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Other"
      }
    ]
}

### Delete the created record
DELETE http://localhost:3000/local/v3.3b/ed-fi/schools/LZRuhjvR1UiLz9Tat_4HOBmlPt_xB_pA20fKyQ
{{auth_header}}


######################## Academic Week


### Create an AcademicWeek record
# reference-validation: true
POST http://localhost:3000/local/v3.3b/ed-fi/academicWeeks
{{auth_header}}
content-type: application/json

{
    "schoolReference": {
        "schoolId": 123
    },
    "weekIdentifier": "123456",
    "beginDate": "2022-12-01",
    "endDate": "2022-12-31",
    "totalInstructionalDays": 30
}


### Get the created record
GET http://localhost:3000/local/v3.3b/ed-fi/academicWeeks/02pe_9hl1wM_jO1vdx8w7iqmhPdEsFofglvS4g
{{auth_header}}


### Update the created record
# reference-validation: true
PUT http://localhost:3000/local/v3.3b/ed-fi/academicWeeks/02pe_9hl1wM_jO1vdx8w7iqmhPdEsFofglvS4g
{{auth_header}}
content-type: application/json

{
    "schoolReference": {
        "schoolId": 123
    },
    "weekIdentifier": "123456",
    "beginDate": "2022-12-01",
    "endDate": "2022-12-31",
    "totalInstructionalDays": 300
}

### Delete the created record
DELETE http://localhost:3000/local/v3.3b/ed-fi/academicWeeks/02pe_9hl1wM_jO1vdx8w7iqmhPdEsFofglvS4g
{{auth_header}}



######################### Query



### Get all schools records
GET http://localhost:3000/local/v3.3b/ed-fi/schools
{{auth_header}}


### Get all academicWeeks records
GET http://localhost:3000/local/v3.3b/ed-fi/academicWeeks
{{auth_header}}


### Query schools
GET http://localhost:3000/local/v3.3b/ed-fi/schools?schoolId=12
{{auth_header}}


### Query academicWeeks
GET http://localhost:3000/local/v3.3b/ed-fi/academicWeeks?schoolReference.schoolId=123
{{auth_header}}

