version: '3'
services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo:4.0.28
    restart: on-failure
    networks:
      - mongo-net
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongo-setup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.0.28
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - mongo-net
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "true" ]
    volumes:
      - mongo-data1:/data/db
      - mongo-datacfg1:/data/configdb

  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.0.28
    expose:
      - 27018
    ports:
      - 27018:27018
    networks:
      - mongo-net
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "true", "--port", "27018" ]
    volumes:
      - mongo-data2:/data/db
      - mongo-datacfg2:/data/configdb

  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.0.28
    expose:
      - 27019
    ports:
      - 27019:27019
    networks:
      - mongo-net
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "true", "--port", "27019" ]
    volumes:
      - mongo-data3:/data/db
      - mongo-datacfg3:/data/configdb

volumes:
  mongo-data1:
  mongo-datacfg1:
  mongo-data2:
  mongo-datacfg2:
  mongo-data3:
  mongo-datacfg3:

networks:
  mongo-net:
