nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://www.myget.org/F/ed-fi/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
