logFilters:
  - level: discard
    pattern: "fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped."

nodeLinker: node-modules

npmRegistryServer: "https://www.myget.org/F/ed-fi/npm/"

npmScopes:
  edfi:
    npmRegistryServer: "https://www.myget.org/F/ed-fi/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
