### Test POST of descriptor

POST http://localhost:3000/ed-fi/contentClassDescriptors/

{
  "codeValue": "Presentation",
  "shortDescription": "Presentation",
  "description": "Presentation",
  "namespace": "uri://ed-fi.org/ContentClassDescriptor"
}

### Test POST of an EducationContent

POST http://localhost:3000/ed-fi/educationContents

{
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430"
}

### Test POST of an EducationContent with two overposted fields
### Result is NoAdditionalPropertiesAllowed
POST http://localhost:3000/ed-fi/educationContents

{
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430",
    "scalarOverpost": "x",
    "objectOverpost": {
      "x": 1
    }
}

#### Test POST of a Section
POST http://localhost:3000/ed-fi/sections

{
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z2"
            }
        }
    ]
}

#### Test POST of a Section with overposts in the classPeriods array
POST http://localhost:3000/ed-fi/sections

{
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1",
                "scalarOverpost": "x"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z2",
                "objectOverpost": {
                    "x": 1
                }
            }
        }
    ]
}

#### Test POST of a Section with non-overpost error - missing classPeriodName in the classPeriods array
POST http://localhost:3000/ed-fi/sections

{
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66
            }
        }
    ]
}
