name: On Pull Request - Dockerfile

on:
  push:
    branches:
      - main
    paths:
      - "Meadowlark-js/Dockerfile"
      - ".github/workflows/on-pullrequest-dockerfile.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Meadowlark-js/Dockerfile"
      - ".github/workflows/on-pullrequest-dockerfile.yml"
  workflow_dispatch:

jobs:
  docker-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        name: Run Linter
        with:
          dockerfile: Meadowlark-js/Dockerfile

      - name: Build the Docker image
        # ...  to confirm no errors occur
        run: npm run docker:build
        working-directory: Meadowlark-js
