name: On Pull Request - Dockerfile

on:
  push:
    branches:
      - main
    paths:
      - "Meadowlark-js/Dockerfile"
      - ".github/workflows/on-pullrequest-dockerfile.yml"
      - "docker/*"
  pull_request:
    branches:
      - main
    paths:
      - "Meadowlark-js/Dockerfile"
      - ".github/workflows/on-pullrequest-dockerfile.yml"
      - "docker/*"
  workflow_dispatch:

permissions: read-all

jobs:
  docker-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        name: Run Linter on Local Dockerfile
        with:
          dockerfile: Meadowlark-js/Dockerfile

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        name: Run Linter on NPM Dockerfile
        with:
          dockerfile: docker/Dockerfile

      - name: Build the NPM Docker image
        # To confirm no errors occur. The "local" one will be built by the e2e
        # testing process.
        run: docker build --build-arg ML_VERSION=latest .
        working-directory: docker
