# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Testing Docker build
on:
  workflow_dispatch:

env:
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  # REF: ${{ github.ref_name }}
  REF: v0.3.6-pre-0
  IMAGE_NAME: ${{ vars.MEADOWLARK_IMAGE_NAME }}

jobs:
  docker-publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Wait 20s
        # Give Azure Artifacts caching a moment to catch up
        run: sleep 20

      - name: Prepare Tags
        id: prepare-tags
        run: |
          BASE="${{ env.IMAGE_NAME }}"

          REF="${{ env.REF }}"
          NPM_VERSION=${REF:1}  # strip off the leading 'v'

          if [[ $REF =~ "pre" ]]
          then
            # Pre-releases get the version and the tag "pre"
            TAGS="${REF},pre"
          else
            # Releases get the version, plus shortened form for minor release.
            # We are not using shortened form for major or using "latest"
            # because they are too imprecise.
            MINOR=`echo ${REF} | awk -F"." '{print $1"."$2}'`
            TAGS="${REF},${MINOR}"
          fi

          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
          echo "NPM_VERSION=$NPM_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c  # v2.5.0

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96  # v4.3.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671  # v4.0.0
        with:
          context: "{{defaultContext}}:docker"
          build-args: ML_VERSION=${{ steps.prepare-tags.outputs.NPM_VERSION }}
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ steps.prepare-tags.outputs.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
